name: Run Karate Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  karate-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Run Karate Tests
        run: |
          mvn clean test
      - name: Debug - List Karate Report Folder
        if: always()
        run: |
          ls -alh target/
          ls -alh target/karate-reports || echo "No reports found"
      - name: Copy Karate Report to deploy folder
        if: always()
        run: |
          mkdir -p output
          cp -r target/karate-reports/. output/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output